/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.polsl.lab.gcdandlcm.ui.view;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import pl.polsl.lab.gcdandlcm.ui.model.GreatestCommonDivisor;
import pl.polsl.lab.gcdandlcm.ui.model.LeastCommonMultiple;
import pl.polsl.lab.gcdandlcm.ui.controller.CalculateButtonController;

/**
 * MainFrame class uses for create main window.
 * 
 * @author Dawid
 * @version 1.0
 */
public class MainFrame extends javax.swing.JPanel {
    
   /**
    * Reference to greatestCommonDivisor class.
    */
    private GreatestCommonDivisor greatestCommonDivisor;
    
    /**
     * Reference to leastCommonMultiple class.
     */
    private LeastCommonMultiple leastCommonMultiple;
    
    /**
     * Reference to CalculateButtonController class.
     */
    private CalculateButtonController calculateButtonController;

    /**
     * To get a first number from field text.
     * @return firstNumberTextField
     */
    public JTextField getFirstNumberTextField() {
        return firstNumberTextField;
    }

    /**
     *  To get a second number from field text.
     * @return secondNumberTextField
     */
    public JTextField getSecondNumberTextField() {
        return secondNumberTextField;
    }

    /**
     * To get a calculation result from field text of greatest common divisor.
     * @return gcdResultTextField
     */
    public JTextField getGcdResultTextField() {
        return gcdResultTextField;
    }

    /**
     * To get a calculation result from field text of least common multiple.
     * @return lcmResultTextField
     */
    public JTextField getLcmResultTextField() {
        return lcmResultTextField;
    }


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        calculateButtonController=new CalculateButtonController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculateButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        firstNumberTextField = new javax.swing.JTextField();
        secondNumberTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gcdResultTextField = new javax.swing.JTextField();
        lcmResultTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Greatest common divisor and Least common multiple ");
        title.setToolTipText("");
        title.setName("title"); // NOI18N

        jLabel1.setText("First number:");

        jLabel2.setText("Second number:");

        gcdResultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcdResultTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Greatest common divisor:");

        jLabel4.setText("Least common multiple:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gcdResultTextField)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNumberTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(secondNumberTextField)
                    .addComponent(lcmResultTextField)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(calculateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gcdResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcmResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(calculateButton)
                .addGap(25, 25, 25))
        );

        calculateButton.getAccessibleContext().setAccessibleName("myButton");
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        
        //send request to controller
        calculateButtonController.calculateGcdAndLcm();
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void gcdResultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcdResultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gcdResultTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField firstNumberTextField;
    private javax.swing.JTextField gcdResultTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lcmResultTextField;
    private javax.swing.JTextField secondNumberTextField;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables


}
